#### This is the playbook to deploy the k8s cluster
#### Check below Change me

- name: Get hosts' variables
  hosts: all
  become: no

- name: Create /etc/hosts file
  hosts: all
  become: yes
  tasks:
  - name: Generate /etc/hosts
    template:
     src: templates/temp-hosts.j2
     dest: /etc/hosts
    register: result
    until: result.failed == false
    retries: 2
    delay: 5
  
- name: Deploy Load Balancers
  hosts: lbg
  become: yes
  vars:
### Change me if you are deploying multiple master nodes
### Change the k8s_vip that will set it to keepalived
### If you are going to deploy Load Balancers, you need to assign a VIP, e.g., 192.168.0.10/24.
    k8s_vip: 'xxx.xxx.xxx/xx'
  roles:
    - role-lbg

- name: Deploy containerd
  hosts: masterg,workerg
  become: yes
  roles:
    - role-containerd

- name: Deploy k8s nodes
  hosts: masterg,workerg
  become: yes
  vars:
### Change me(must)
### k8s_vip: If you are going to deploy Load Balancers, this k8s_vip should the same as above, e.g., 192.168.0.10
###          If you are not going to deploying multiple master nodes, this k8s_vip should be MASTER-NODE-IP
### k8s_version: This playbook is going to install "1.25.0"
### pod_cidr: This ip pool will be will by pods. If change it, make sure is /16
### k8s_packages: The verison should be the same as k8s_version.
    k8s_vip: "xxx.xxx.xxx.xxx"
    k8s_version: "1.25.0"
    pod_cidr: "10.10.0.0/16"
    k8s_packages:
    - "kubelet=1.25.0-00"
    - "kubeadm=1.25.0-00"
    - "kubectl=1.25.0-00"
  roles:
    - role-k8s
